# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GuiMinDistancesBetweenTwoMODfiles.ui'
#
# Created: Fri May 05 15:12:15 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(890, 812)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Carlito"))
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.InputOutputTab = QtGui.QWidget()
        self.InputOutputTab.setObjectName(_fromUtf8("InputOutputTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.InputOutputTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayoutInput = QtGui.QVBoxLayout()
        self.verticalLayoutInput.setObjectName(_fromUtf8("verticalLayoutInput"))
        self.InputLabel = QtGui.QLabel(self.InputOutputTab)
        self.InputLabel.setObjectName(_fromUtf8("InputLabel"))
        self.verticalLayoutInput.addWidget(self.InputLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelMOD1 = QtGui.QLabel(self.InputOutputTab)
        self.labelMOD1.setObjectName(_fromUtf8("labelMOD1"))
        self.horizontalLayout.addWidget(self.labelMOD1)
        self.lineEditMOD1 = QtGui.QLineEdit(self.InputOutputTab)
        self.lineEditMOD1.setObjectName(_fromUtf8("lineEditMOD1"))
        self.horizontalLayout.addWidget(self.lineEditMOD1)
        self.BrowseMOD1 = QtGui.QPushButton(self.InputOutputTab)
        self.BrowseMOD1.setObjectName(_fromUtf8("BrowseMOD1"))
        self.horizontalLayout.addWidget(self.BrowseMOD1)
        self.verticalLayoutInput.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelCSV1 = QtGui.QLabel(self.InputOutputTab)
        self.labelCSV1.setObjectName(_fromUtf8("labelCSV1"))
        self.horizontalLayout_2.addWidget(self.labelCSV1)
        self.lineEditCSV1 = QtGui.QLineEdit(self.InputOutputTab)
        self.lineEditCSV1.setObjectName(_fromUtf8("lineEditCSV1"))
        self.horizontalLayout_2.addWidget(self.lineEditCSV1)
        self.BrowseCSV1 = QtGui.QPushButton(self.InputOutputTab)
        self.BrowseCSV1.setObjectName(_fromUtf8("BrowseCSV1"))
        self.horizontalLayout_2.addWidget(self.BrowseCSV1)
        self.verticalLayoutInput.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayoutInput)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.InputLabel_2 = QtGui.QLabel(self.InputOutputTab)
        self.InputLabel_2.setObjectName(_fromUtf8("InputLabel_2"))
        self.verticalLayout_2.addWidget(self.InputLabel_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelMOD2 = QtGui.QLabel(self.InputOutputTab)
        self.labelMOD2.setObjectName(_fromUtf8("labelMOD2"))
        self.horizontalLayout_3.addWidget(self.labelMOD2)
        self.lineEditMOD2 = QtGui.QLineEdit(self.InputOutputTab)
        self.lineEditMOD2.setObjectName(_fromUtf8("lineEditMOD2"))
        self.horizontalLayout_3.addWidget(self.lineEditMOD2)
        self.BrowseMOD2 = QtGui.QPushButton(self.InputOutputTab)
        self.BrowseMOD2.setObjectName(_fromUtf8("BrowseMOD2"))
        self.horizontalLayout_3.addWidget(self.BrowseMOD2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelCSV2 = QtGui.QLabel(self.InputOutputTab)
        self.labelCSV2.setObjectName(_fromUtf8("labelCSV2"))
        self.horizontalLayout_4.addWidget(self.labelCSV2)
        self.lineEditCSV2 = QtGui.QLineEdit(self.InputOutputTab)
        self.lineEditCSV2.setObjectName(_fromUtf8("lineEditCSV2"))
        self.horizontalLayout_4.addWidget(self.lineEditCSV2)
        self.BrowseCSV2 = QtGui.QPushButton(self.InputOutputTab)
        self.BrowseCSV2.setObjectName(_fromUtf8("BrowseCSV2"))
        self.horizontalLayout_4.addWidget(self.BrowseCSV2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelBins = QtGui.QLabel(self.InputOutputTab)
        self.labelBins.setObjectName(_fromUtf8("labelBins"))
        self.horizontalLayout_7.addWidget(self.labelBins)
        self.spinBoxNumBins = QtGui.QSpinBox(self.InputOutputTab)
        self.spinBoxNumBins.setMinimum(2)
        self.spinBoxNumBins.setMaximum(300)
        self.spinBoxNumBins.setProperty("value", 20)
        self.spinBoxNumBins.setObjectName(_fromUtf8("spinBoxNumBins"))
        self.horizontalLayout_7.addWidget(self.spinBoxNumBins)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.labelRadius = QtGui.QLabel(self.InputOutputTab)
        self.labelRadius.setObjectName(_fromUtf8("labelRadius"))
        self.horizontalLayout_7.addWidget(self.labelRadius)
        self.lineEditRadius = QtGui.QLineEdit(self.InputOutputTab)
        self.lineEditRadius.setObjectName(_fromUtf8("lineEditRadius"))
        self.horizontalLayout_7.addWidget(self.lineEditRadius)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.widget_2 = QtGui.QWidget(self.InputOutputTab)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout.addWidget(self.widget_2)
        self.StartButton = QtGui.QPushButton(self.InputOutputTab)
        self.StartButton.setObjectName(_fromUtf8("StartButton"))
        self.verticalLayout.addWidget(self.StartButton)
        spacerItem1 = QtGui.QSpacerItem(17, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.line = QtGui.QFrame(self.InputOutputTab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_Output = QtGui.QLabel(self.InputOutputTab)
        self.label_Output.setObjectName(_fromUtf8("label_Output"))
        self.verticalLayout_6.addWidget(self.label_Output)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_OutMOD = QtGui.QLabel(self.InputOutputTab)
        self.label_OutMOD.setObjectName(_fromUtf8("label_OutMOD"))
        self.horizontalLayout_5.addWidget(self.label_OutMOD)
        self.lineEdit_OutMOD = QtGui.QLineEdit(self.InputOutputTab)
        self.lineEdit_OutMOD.setObjectName(_fromUtf8("lineEdit_OutMOD"))
        self.horizontalLayout_5.addWidget(self.lineEdit_OutMOD)
        self.BrowseOutMOD = QtGui.QPushButton(self.InputOutputTab)
        self.BrowseOutMOD.setObjectName(_fromUtf8("BrowseOutMOD"))
        self.horizontalLayout_5.addWidget(self.BrowseOutMOD)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_OutCSV = QtGui.QLabel(self.InputOutputTab)
        self.label_OutCSV.setObjectName(_fromUtf8("label_OutCSV"))
        self.horizontalLayout_6.addWidget(self.label_OutCSV)
        self.lineEdit_OutCSV = QtGui.QLineEdit(self.InputOutputTab)
        self.lineEdit_OutCSV.setObjectName(_fromUtf8("lineEdit_OutCSV"))
        self.horizontalLayout_6.addWidget(self.lineEdit_OutCSV)
        self.BrowseOutCSV = QtGui.QPushButton(self.InputOutputTab)
        self.BrowseOutCSV.setObjectName(_fromUtf8("BrowseOutCSV"))
        self.horizontalLayout_6.addWidget(self.BrowseOutCSV)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.pushButton_SAVE = QtGui.QPushButton(self.InputOutputTab)
        self.pushButton_SAVE.setEnabled(False)
        self.pushButton_SAVE.setObjectName(_fromUtf8("pushButton_SAVE"))
        self.verticalLayout_5.addWidget(self.pushButton_SAVE)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.MytextBrowser = QtGui.QTextBrowser(self.InputOutputTab)
        self.MytextBrowser.setObjectName(_fromUtf8("MytextBrowser"))
        self.verticalLayout.addWidget(self.MytextBrowser)
        self.tabWidget.addTab(self.InputOutputTab, _fromUtf8(""))
        self.GraficTab = QtGui.QWidget()
        self.GraficTab.setObjectName(_fromUtf8("GraficTab"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.GraficTab)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.MyGraficwidget = QtGui.QWidget(self.GraficTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MyGraficwidget.sizePolicy().hasHeightForWidth())
        self.MyGraficwidget.setSizePolicy(sizePolicy)
        self.MyGraficwidget.setObjectName(_fromUtf8("MyGraficwidget"))
        self.MyGraficLayout = QtGui.QVBoxLayout(self.MyGraficwidget)
        self.MyGraficLayout.setMargin(0)
        self.MyGraficLayout.setObjectName(_fromUtf8("MyGraficLayout"))
        self.verticalLayout_9.addWidget(self.MyGraficwidget)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label = QtGui.QLabel(self.GraficTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_15.addWidget(self.label)
        self.doubleSpinBox_LimitLow = QtGui.QDoubleSpinBox(self.GraficTab)
        self.doubleSpinBox_LimitLow.setProperty("value", 1.0)
        self.doubleSpinBox_LimitLow.setObjectName(_fromUtf8("doubleSpinBox_LimitLow"))
        self.horizontalLayout_15.addWidget(self.doubleSpinBox_LimitLow)
        self.label_3 = QtGui.QLabel(self.GraficTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_15.addWidget(self.label_3)
        self.doubleSpinBox_LimitHigh = QtGui.QDoubleSpinBox(self.GraficTab)
        self.doubleSpinBox_LimitHigh.setProperty("value", 6.0)
        self.doubleSpinBox_LimitHigh.setObjectName(_fromUtf8("doubleSpinBox_LimitHigh"))
        self.horizontalLayout_15.addWidget(self.doubleSpinBox_LimitHigh)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.checkBox = QtGui.QCheckBox(self.GraficTab)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_15.addWidget(self.checkBox)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.tabWidget.addTab(self.GraficTab, _fromUtf8(""))
        self.ListTab = QtGui.QWidget()
        self.ListTab.setObjectName(_fromUtf8("ListTab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.ListTab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tableView = QtGui.QTableView(self.ListTab)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_4.addWidget(self.tableView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.ListTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 890, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuMain = QtGui.QMenu(self.menuBar)
        self.menuMain.setObjectName(_fromUtf8("menuMain"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.menuMain.addAction(self.actionClose)
        self.menuBar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Minimal distances between two MOD models", None))
        self.InputLabel.setText(_translate("MainWindow", "Input Object 1", None))
        self.labelMOD1.setText(_translate("MainWindow", "MOD file", None))
        self.lineEditMOD1.setText(_translate("MainWindow", "", None)) #  "D:/Data/ExperimentalData/Oxford/TransportMichael/G53a_b4_ves1_fromIter5_bin0.5_fromIter0_bin0.5_MOTL_Tom1_Iter2_remdup_2.0.mod", None))
        self.BrowseMOD1.setText(_translate("MainWindow", "browse", None))
        self.labelCSV1.setText(_translate("MainWindow", "CSV file", None))
        self.lineEditCSV1.setText(_translate("MainWindow", "", None)) #  "D:/Data/ExperimentalData/Oxford/TransportMichael/G53a_b4_ves1_fromIter5_bin0.5_fromIter0_bin0.5_fromIter2_remdup2.0_MOTL_Tom1_Iter6.csv", None))
        self.BrowseCSV1.setText(_translate("MainWindow", "browse", None))
        self.InputLabel_2.setText(_translate("MainWindow", "Input Object 2", None))
        self.labelMOD2.setText(_translate("MainWindow", "MOD file", None))
        self.lineEditMOD2.setText(_translate("MainWindow",  "", None)) # "D:/Data/ExperimentalData/Oxford/TransportMichael/run1_b4_NEC_C-capsids_fromIter7_hexons_fromIter0_remedge2.0_MOTL_Tom9_Iter6_remdup_0.0.mod", None))
        self.BrowseMOD2.setText(_translate("MainWindow", "browse", None))
        self.labelCSV2.setText(_translate("MainWindow", "CSV file", None))
        self.lineEditCSV2.setText(_translate("MainWindow", "", None)) # "D:/Data/ExperimentalData/Oxford/TransportMichael/run1_b4_NEC_C-capsids_fromIter7_hexons_fromIter0_remedge2.0_fromIter6_remdup0.0_MOTL_Tom9_Iter5.csv", None))
        self.BrowseCSV2.setText(_translate("MainWindow", "browse", None))
        self.labelBins.setText(_translate("MainWindow", "Number of bins", None))
        self.labelRadius.setText(_translate("MainWindow", "Neighbourhood radius", None))
        self.lineEditRadius.setText(_translate("MainWindow", "9", None))
        self.StartButton.setText(_translate("MainWindow", "Start", None))
        self.label_Output.setText(_translate("MainWindow", "Output", None))
        self.label_OutMOD.setText(_translate("MainWindow", "MOD file", None))
        self.lineEdit_OutMOD.setText(_translate("MainWindow", "dumbmemod", None))
        self.BrowseOutMOD.setText(_translate("MainWindow", "browse", None))
        self.label_OutCSV.setText(_translate("MainWindow", "CSV file", None))
        self.lineEdit_OutCSV.setText(_translate("MainWindow", "dumbmecsv", None))
        self.BrowseOutCSV.setText(_translate("MainWindow", "browse", None))
        self.pushButton_SAVE.setText(_translate("MainWindow", "Save", None))
        self.MytextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Carlito\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\'; font-size:11pt;\">This program compares the positions of points in two model files. It computes the nearest neighbours of the first file and prints out some histograms.</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InputOutputTab), _translate("MainWindow", "Input / Output", None))
        self.label.setText(_translate("MainWindow", "lower limit", None))
        self.label_3.setText(_translate("MainWindow", "upper limit", None))
        self.checkBox.setText(_translate("MainWindow", "show limits", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GraficTab), _translate("MainWindow", "Grafics", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ListTab), _translate("MainWindow", "Listoutput", None))
        self.menuMain.setTitle(_translate("MainWindow", "Main", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))

