# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SphericalViewer.ui'
#
# Created: Wed May 03 15:12:03 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1083, 791)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_input = QtGui.QWidget()
        self.tab_input.setObjectName(_fromUtf8("tab_input"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_input)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_mrc = QtGui.QLabel(self.tab_input)
        self.label_mrc.setObjectName(_fromUtf8("label_mrc"))
        self.horizontalLayout_2.addWidget(self.label_mrc)
        self.lineEdit_mrc = QtGui.QLineEdit(self.tab_input)
        self.lineEdit_mrc.setObjectName(_fromUtf8("lineEdit_mrc"))
        self.horizontalLayout_2.addWidget(self.lineEdit_mrc)
        self.pushButton_mrc = QtGui.QPushButton(self.tab_input)
        self.pushButton_mrc.setObjectName(_fromUtf8("pushButton_mrc"))
        self.horizontalLayout_2.addWidget(self.pushButton_mrc)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_mod = QtGui.QLabel(self.tab_input)
        self.label_mod.setObjectName(_fromUtf8("label_mod"))
        self.horizontalLayout_3.addWidget(self.label_mod)
        self.lineEdit_mod = QtGui.QLineEdit(self.tab_input)
        self.lineEdit_mod.setObjectName(_fromUtf8("lineEdit_mod"))
        self.horizontalLayout_3.addWidget(self.lineEdit_mod)
        self.pushButton_mod = QtGui.QPushButton(self.tab_input)
        self.pushButton_mod.setObjectName(_fromUtf8("pushButton_mod"))
        self.horizontalLayout_3.addWidget(self.pushButton_mod)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.textBrowser_OutputInfo = QtGui.QTextBrowser(self.tab_input)
        self.textBrowser_OutputInfo.setObjectName(_fromUtf8("textBrowser_OutputInfo"))
        self.verticalLayout_6.addWidget(self.textBrowser_OutputInfo)
        self.pushButton_Start = QtGui.QPushButton(self.tab_input)
        self.pushButton_Start.setObjectName(_fromUtf8("pushButton_Start"))
        self.verticalLayout_6.addWidget(self.pushButton_Start)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_input, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.widget_grafic_x = QtGui.QWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_grafic_x.sizePolicy().hasHeightForWidth())
        self.widget_grafic_x.setSizePolicy(sizePolicy)
        self.widget_grafic_x.setObjectName(_fromUtf8("widget_grafic_x"))
        self.verticalLayout_grafic_x = QtGui.QVBoxLayout(self.widget_grafic_x)
        self.verticalLayout_grafic_x.setMargin(0)
        self.verticalLayout_grafic_x.setObjectName(_fromUtf8("verticalLayout_grafic_x"))
        self.verticalLayout_11.addWidget(self.widget_grafic_x)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_slicex = QtGui.QLabel(self.tab)
        self.label_slicex.setObjectName(_fromUtf8("label_slicex"))
        self.horizontalLayout_20.addWidget(self.label_slicex)
        self.spinBox_slicex = QtGui.QSpinBox(self.tab)
        self.spinBox_slicex.setObjectName(_fromUtf8("spinBox_slicex"))
        self.horizontalLayout_20.addWidget(self.spinBox_slicex)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.horizontalScrollBar_slicex = QtGui.QScrollBar(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar_slicex.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar_slicex.setSizePolicy(sizePolicy)
        self.horizontalScrollBar_slicex.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_slicex.setObjectName(_fromUtf8("horizontalScrollBar_slicex"))
        self.verticalLayout_11.addWidget(self.horizontalScrollBar_slicex)
        self.horizontalLayout_23.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.widget_grafic_y = QtGui.QWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_grafic_y.sizePolicy().hasHeightForWidth())
        self.widget_grafic_y.setSizePolicy(sizePolicy)
        self.widget_grafic_y.setObjectName(_fromUtf8("widget_grafic_y"))
        self.verticalLayout_grafic_y = QtGui.QVBoxLayout(self.widget_grafic_y)
        self.verticalLayout_grafic_y.setMargin(0)
        self.verticalLayout_grafic_y.setObjectName(_fromUtf8("verticalLayout_grafic_y"))
        self.verticalLayout_12.addWidget(self.widget_grafic_y)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_slicey = QtGui.QLabel(self.tab)
        self.label_slicey.setObjectName(_fromUtf8("label_slicey"))
        self.horizontalLayout_21.addWidget(self.label_slicey)
        self.spinBox_slicey = QtGui.QSpinBox(self.tab)
        self.spinBox_slicey.setObjectName(_fromUtf8("spinBox_slicey"))
        self.horizontalLayout_21.addWidget(self.spinBox_slicey)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_21)
        self.horizontalScrollBar_slicey = QtGui.QScrollBar(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar_slicey.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar_slicey.setSizePolicy(sizePolicy)
        self.horizontalScrollBar_slicey.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_slicey.setObjectName(_fromUtf8("horizontalScrollBar_slicey"))
        self.verticalLayout_12.addWidget(self.horizontalScrollBar_slicey)
        self.horizontalLayout_23.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.widget_grafic_z = QtGui.QWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_grafic_z.sizePolicy().hasHeightForWidth())
        self.widget_grafic_z.setSizePolicy(sizePolicy)
        self.widget_grafic_z.setObjectName(_fromUtf8("widget_grafic_z"))
        self.verticalLayout_grafic_z = QtGui.QVBoxLayout(self.widget_grafic_z)
        self.verticalLayout_grafic_z.setMargin(0)
        self.verticalLayout_grafic_z.setObjectName(_fromUtf8("verticalLayout_grafic_z"))
        self.verticalLayout_13.addWidget(self.widget_grafic_z)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_slicez = QtGui.QLabel(self.tab)
        self.label_slicez.setObjectName(_fromUtf8("label_slicez"))
        self.horizontalLayout_22.addWidget(self.label_slicez)
        self.spinBox_slicez = QtGui.QSpinBox(self.tab)
        self.spinBox_slicez.setObjectName(_fromUtf8("spinBox_slicez"))
        self.horizontalLayout_22.addWidget(self.spinBox_slicez)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem3)
        self.verticalLayout_13.addLayout(self.horizontalLayout_22)
        self.horizontalScrollBar_slicez = QtGui.QScrollBar(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar_slicez.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar_slicez.setSizePolicy(sizePolicy)
        self.horizontalScrollBar_slicez.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_slicez.setObjectName(_fromUtf8("horizontalScrollBar_slicez"))
        self.verticalLayout_13.addWidget(self.horizontalScrollBar_slicez)
        self.horizontalLayout_23.addLayout(self.verticalLayout_13)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_23)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_grafic = QtGui.QWidget()
        self.tab_grafic.setObjectName(_fromUtf8("tab_grafic"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_grafic)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.myGraficwidget_Chart = QtGui.QWidget(self.tab_grafic)
        self.myGraficwidget_Chart.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myGraficwidget_Chart.sizePolicy().hasHeightForWidth())
        self.myGraficwidget_Chart.setSizePolicy(sizePolicy)
        self.myGraficwidget_Chart.setObjectName(_fromUtf8("myGraficwidget_Chart"))
        self.verticalLayout_Chart = QtGui.QVBoxLayout(self.myGraficwidget_Chart)
        self.verticalLayout_Chart.setMargin(0)
        self.verticalLayout_Chart.setObjectName(_fromUtf8("verticalLayout_Chart"))
        self.verticalLayout.addWidget(self.myGraficwidget_Chart)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_radius = QtGui.QLabel(self.tab_grafic)
        self.label_radius.setObjectName(_fromUtf8("label_radius"))
        self.horizontalLayout.addWidget(self.label_radius)
        self.doubleSpinBox_radius = QtGui.QDoubleSpinBox(self.tab_grafic)
        self.doubleSpinBox_radius.setEnabled(True)
        self.doubleSpinBox_radius.setObjectName(_fromUtf8("doubleSpinBox_radius"))
        self.horizontalLayout.addWidget(self.doubleSpinBox_radius)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label_center = QtGui.QLabel(self.tab_grafic)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_center.sizePolicy().hasHeightForWidth())
        self.label_center.setSizePolicy(sizePolicy)
        self.label_center.setObjectName(_fromUtf8("label_center"))
        self.horizontalLayout.addWidget(self.label_center)
        self.doubleSpinBox_centerx = QtGui.QDoubleSpinBox(self.tab_grafic)
        self.doubleSpinBox_centerx.setObjectName(_fromUtf8("doubleSpinBox_centerx"))
        self.horizontalLayout.addWidget(self.doubleSpinBox_centerx)
        self.doubleSpinBox_centery = QtGui.QDoubleSpinBox(self.tab_grafic)
        self.doubleSpinBox_centery.setObjectName(_fromUtf8("doubleSpinBox_centery"))
        self.horizontalLayout.addWidget(self.doubleSpinBox_centery)
        self.doubleSpinBox_centerz = QtGui.QDoubleSpinBox(self.tab_grafic)
        self.doubleSpinBox_centerz.setObjectName(_fromUtf8("doubleSpinBox_centerz"))
        self.horizontalLayout.addWidget(self.doubleSpinBox_centerz)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_10.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_grafic, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1083, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionOpen_MOD_file = QtGui.QAction(MainWindow)
        self.actionOpen_MOD_file.setObjectName(_fromUtf8("actionOpen_MOD_file"))
        self.actionOpen_MRC_file = QtGui.QAction(MainWindow)
        self.actionOpen_MRC_file.setObjectName(_fromUtf8("actionOpen_MRC_file"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.horizontalScrollBar_slicex, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_slicex.setValue)
        QtCore.QObject.connect(self.spinBox_slicex, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalScrollBar_slicex.setValue)
        QtCore.QObject.connect(self.spinBox_slicey, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalScrollBar_slicey.setValue)
        QtCore.QObject.connect(self.horizontalScrollBar_slicey, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_slicey.setValue)
        QtCore.QObject.connect(self.horizontalScrollBar_slicez, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_slicez.setValue)
        QtCore.QObject.connect(self.spinBox_slicez, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalScrollBar_slicez.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Spherical partical surface viewer", None))
        self.label_mrc.setText(_translate("MainWindow", "MRC-file", None))
        self.lineEdit_mrc.setText(_translate("MainWindow", "D:/Data/ExperimentalData/Oxford/G35a_b4_filt.rec", None))
        self.pushButton_mrc.setText(_translate("MainWindow", "Browse", None))
        self.label_mod.setText(_translate("MainWindow", "Mod-file", None))
        self.lineEdit_mod.setText(_translate("MainWindow", "D:/Data/ExperimentalData/Oxford/testmod_G35a_b4.mod", None))
        self.pushButton_mod.setText(_translate("MainWindow", "Browse", None))
        self.textBrowser_OutputInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">This program allows to view the surface of a spherical particle. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">The tomogram is assumedto be an mrc file and the mod file contains some points on the surface. These points are used to guess the center and the radius of the surface via least square approximation.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"> </span></p></body></html>", None))
        self.pushButton_Start.setText(_translate("MainWindow", "Start", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_input), _translate("MainWindow", "Input", None))
        self.label_slicex.setText(_translate("MainWindow", "x", None))
        self.label_slicey.setText(_translate("MainWindow", "y", None))
        self.label_slicez.setText(_translate("MainWindow", "z", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "x/y/z slicer", None))
        self.label_radius.setText(_translate("MainWindow", "Radius", None))
        self.label_center.setText(_translate("MainWindow", "Center (x,y,z)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_grafic), _translate("MainWindow", "Grafics", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionOpen_MOD_file.setText(_translate("MainWindow", "Open MOD file", None))
        self.actionOpen_MRC_file.setText(_translate("MainWindow", "Open MRC file", None))

