#!/usr/bin/env python3
import sys as _sys, os as _os
_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))


def main():
    import argparse
    from PEET2Dynamo import extract_pcles_for_dynamo_from_prmfile

    parser = argparse.ArgumentParser(description=("Extract particles and create table files for use with Dynamo, from a PEET prm file."))

    parser.add_argument('prmfile', help="The PEET prm file to convert.")
    parser.add_argument('iteration', help="The iteration from the PEET run to convert", type=int)
    parser.add_argument('boxsize', help='The size of the box to extract, in x,y,z order.')
    parser.add_argument('out_dir', help='Output directory for files.')
    parser.add_argument('--out_table', help="Name of output table file. Default is particles.tbl", default='particles.tbl')
    parser.add_argument('--no_extraction', help='Skip particle extraction and just create the particle lists.', action="store_false")
    parser.add_argument('--do_not_rotate', help='Do not rotate particles around x axis by 90 degrees.', action="store_false")


    args = parser.parse_args()
    boxsize = [int(x) for x in args.boxsize.split(',')]

    extract_pcles_for_dynamo_from_prmfile(args.prmfile, args.iteration, boxsize, args.out_dir, extpcles=args.no_extraction, zaxis=args.do_not_rotate)



if __name__ == '__main__':
    main()
