#!/usr/bin/env python3
import sys as _sys, os as _os
_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))


def main():
    import argparse
    from star_to_newstack import *

    parser = argparse.ArgumentParser(description=('Takes an input Relion data star file and creates a text file for use with newstack -fileinlist, to create a stack of all relevant particles.'))
    parser.add_argument('starfile', help='The name of the Relion data star file.')
    parser.add_argument('outfile', help='The desired name of the output file.')

    args = parser.parse_args()

    star_to_newstack_input(args.starfile, args.outfile)



if __name__ == '__main__':
    main()
